# Generated by Django 4.1.1 on 2022-10-26 00:53

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(max_length=100, verbose_name='Descripcion')),
                ('imagen', models.ImageField(upload_to='premios/', verbose_name='Imagen')),
                ('initial_stock', models.IntegerField(verbose_name='Stock inicial')),
                ('current_stock', models.IntegerField(default=0, verbose_name='Stock actual')),
                ('prizes_awarded', models.IntegerField(default=0, verbose_name='Premios entregados')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('L', 'Legendaria'), ('E', 'Epica'), ('R', 'Rara'), ('C', 'Comun')], default='C', max_length=1, verbose_name='Categoria')),
                ('juego', models.CharField(choices=[('T', 'Traga Monedas')], default='T', max_length=1, verbose_name='Juego')),
            ],
            options={
                'verbose_name': 'Premio',
                'verbose_name_plural': 'Premios',
                'ordering': ['id', 'name', 'description', 'initial_stock', 'current_stock', 'prizes_awarded'],
            },
        ),
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo Electronico')),
                ('code', models.CharField(max_length=6, verbose_name='Codigo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'RecuperarContraseña',
                'verbose_name_plural': 'RecuperarContraseñas',
                'ordering': ['email', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateTimeField(verbose_name='Fecha inicio juego')),
                ('end_date', models.DateTimeField(verbose_name='Fecha fin juego')),
                ('modification_date', models.DateTimeField(null=True, verbose_name='Fecha  modificacion juego')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Game Name')),
                ('description', models.CharField(max_length=250, verbose_name='Game description')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
            },
        ),
        migrations.CreateModel(
            name='GameDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de fin')),
                ('modification_date', models.DateTimeField(verbose_name='Fecha de modificacion')),
                ('juego', models.CharField(choices=[('T', 'Traga Monedas')], default='T', max_length=1, verbose_name='Juego')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenesJuegos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('imagen', models.ImageField(upload_to='imagenes_juegos/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'ImagenJuego',
                'verbose_name_plural': 'ImagenesJuegos',
                'ordering': ['imagen'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(max_length=100, verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('names', models.CharField(max_length=100, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo Electronico')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('phone', models.CharField(max_length=10, verbose_name='Telefono')),
                ('sex', models.CharField(choices=[('N', 'Ninguno'), ('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1, verbose_name='Sexo')),
                ('address', models.CharField(max_length=100, verbose_name='Direccion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('is_active', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJuegos.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['id', 'username', 'cedula', 'names', 'surnames', 'email', 'phone'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RolPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJuegos.permission', verbose_name='Permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJuegos.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'RolPermiso',
                'verbose_name_plural': 'RolPermisos',
                'ordering': ['rol', 'permission'],
            },
        ),
        migrations.CreateModel(
            name='Probabilidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('porcent_win', models.PositiveIntegerField(verbose_name='porcent_win')),
                ('winners_limit', models.PositiveIntegerField(verbose_name='porcent_win')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificacion')),
                ('is_active', models.BooleanField(default=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJuegos.game', verbose_name='Juego')),
            ],
            options={
                'verbose_name': 'Probabilidad',
                'verbose_name_plural': 'Probabilidades',
            },
        ),
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('cedula', models.CharField(db_index=True, max_length=10, verbose_name='Cédula')),
                ('names', models.CharField(max_length=100, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('username', models.CharField(db_index=True, max_length=50, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(db_index=True, max_length=100, verbose_name='Correo Electronico')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('phone', models.CharField(max_length=10, verbose_name='Telefono')),
                ('sex', models.CharField(choices=[('N', 'Ninguno'), ('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1, verbose_name='Sexo')),
                ('address', models.CharField(max_length=100, verbose_name='Direccion')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificacion')),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AppJuegos.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'historical Usuario',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProbabilidad',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('porcent_win', models.PositiveIntegerField(verbose_name='porcent_win')),
                ('winners_limit', models.PositiveIntegerField(verbose_name='porcent_win')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificacion')),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('game_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AppJuegos.game', verbose_name='Juego')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Probabilidad',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGame',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('start_date', models.DateTimeField(verbose_name='Fecha inicio juego')),
                ('end_date', models.DateTimeField(verbose_name='Fecha fin juego')),
                ('modification_date', models.DateTimeField(null=True, verbose_name='Fecha  modificacion juego')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Game Name')),
                ('description', models.CharField(max_length=250, verbose_name='Game description')),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Juego',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalClient',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('cedula', models.CharField(db_index=True, max_length=10, verbose_name='Cédula')),
                ('names', models.CharField(max_length=100, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(db_index=True, max_length=100, verbose_name='Correo Electronico')),
                ('phone', models.CharField(max_length=10, verbose_name='Telefono')),
                ('sex', models.CharField(choices=[('N', 'Ninguno'), ('F', 'Femenino'), ('M', 'Masculino')], default='N', max_length=1, verbose_name='Sexo')),
                ('address', models.CharField(max_length=500, verbose_name='Direccion')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificacion')),
                ('state', models.CharField(choices=[('Ninguno', 'Ninguno'), ('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Deshabilitado', 'Desabilitado')], default='Ninguno', max_length=100, verbose_name='Estado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_client_modify', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modifica')),
                ('user_client_register', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registra')),
            ],
            options={
                'verbose_name': 'historical Cliente',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAward',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(max_length=100, verbose_name='Descripcion')),
                ('imagen', models.TextField(max_length=100, verbose_name='Imagen')),
                ('initial_stock', models.IntegerField(verbose_name='Stock inicial')),
                ('current_stock', models.IntegerField(default=0, verbose_name='Stock actual')),
                ('prizes_awarded', models.IntegerField(default=0, verbose_name='Premios entregados')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificacion')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('L', 'Legendaria'), ('E', 'Epica'), ('R', 'Rara'), ('C', 'Comun')], default='C', max_length=1, verbose_name='Categoria')),
                ('juego', models.CharField(choices=[('T', 'Traga Monedas')], default='T', max_length=1, verbose_name='Juego')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_modify', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modifica')),
                ('user_register', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registra')),
            ],
            options={
                'verbose_name': 'historical Premio',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('names', models.CharField(max_length=100, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo Electronico')),
                ('phone', models.CharField(max_length=10, verbose_name='Telefono')),
                ('sex', models.CharField(choices=[('N', 'Ninguno'), ('F', 'Femenino'), ('M', 'Masculino')], default='N', max_length=1, verbose_name='Sexo')),
                ('address', models.CharField(max_length=500, verbose_name='Direccion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('state', models.CharField(choices=[('Ninguno', 'Ninguno'), ('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Deshabilitado', 'Desabilitado')], default='Ninguno', max_length=100, verbose_name='Estado')),
                ('user_client_modify', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_client_modify', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modifica')),
                ('user_client_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_client_register', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registra')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id', 'cedula', 'names', 'surnames', 'email', 'phone'],
            },
        ),
        migrations.CreateModel(
            name='AwardGame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJuegos.game', verbose_name='Juego')),
                ('premio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_in_game', to='AppJuegos.award', verbose_name='Premio')),
            ],
            options={
                'verbose_name': 'Premio Juego',
                'verbose_name_plural': 'Premios Juegos',
            },
        ),
        migrations.AddField(
            model_name='award',
            name='user_modify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_modify', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modifica'),
        ),
        migrations.AddField(
            model_name='award',
            name='user_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_register', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registra'),
        ),
    ]
