# Generated by Django 4.1 on 2022-08-29 11:10

import AppJuegos.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(max_length=255, verbose_name='Descripcion')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('modified', AppJuegos.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(max_length=255, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Seccion',
                'verbose_name_plural': 'Secciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Cedula')),
                ('first_name', models.CharField(max_length=50, verbose_name='Primer Nombre')),
                ('second_name', models.CharField(max_length=50, verbose_name='Segundo Nombre')),
                ('father_last_name', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('mother_last_name', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electronico')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('phone', models.CharField(max_length=10, verbose_name='Telefono')),
                ('sex', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('birthday', models.DateField(default=django.utils.timezone.now, verbose_name='Cumpleaños')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('modified', AppJuegos.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('last_session', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['id', 'first_name', 'father_last_name', 'mother_last_name', 'email', 'state'],
            },
        ),
        migrations.CreateModel(
            name='UserRol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJuegos.rol', verbose_name='Rol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJuegos.user', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'UsuarioRol',
                'verbose_name_plural': 'UsuarioRoles',
                'ordering': ['user', 'rol'],
            },
        ),
        migrations.CreateModel(
            name='RolPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJuegos.permission', verbose_name='Permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJuegos.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'RolPermiso',
                'verbose_name_plural': 'RolPermisos',
                'ordering': ['rol', 'permission'],
            },
        ),
        migrations.AddField(
            model_name='permission',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJuegos.section', verbose_name='Seccion'),
        ),
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.CharField(db_index=True, max_length=10, verbose_name='Cedula')),
                ('first_name', models.CharField(max_length=50, verbose_name='Primer Nombre')),
                ('second_name', models.CharField(max_length=50, verbose_name='Segundo Nombre')),
                ('father_last_name', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('mother_last_name', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('email', models.EmailField(db_index=True, max_length=255, verbose_name='Correo Electronico')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('phone', models.CharField(max_length=10, verbose_name='Telefono')),
                ('sex', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('birthday', models.DateField(default=django.utils.timezone.now, verbose_name='Cumpleaños')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('modified', AppJuegos.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('last_session', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, verbose_name='Estado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Usuario',
                'verbose_name_plural': 'historical Usuarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
