# Generated by Django 4.1.1 on 2022-09-09 10:26

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(max_length=100, verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('names', models.CharField(max_length=100, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo Electronico')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('phone', models.CharField(max_length=10, verbose_name='Telefono')),
                ('sex', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1, verbose_name='Sexo')),
                ('address', models.CharField(max_length=100, verbose_name='Direccion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('last_session', models.DateTimeField(auto_now=True, verbose_name='Ultima sesion')),
                ('is_active', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJuegos.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['id', 'username', 'cedula', 'names', 'surnames', 'email', 'phone'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RolPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJuegos.permission', verbose_name='Permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJuegos.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'RolPermiso',
                'verbose_name_plural': 'RolPermisos',
                'ordering': ['rol', 'permission'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('cedula', models.CharField(db_index=True, max_length=10, verbose_name='Cédula')),
                ('names', models.CharField(max_length=100, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('username', models.CharField(db_index=True, max_length=50, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(db_index=True, max_length=100, verbose_name='Correo Electronico')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('phone', models.CharField(max_length=10, verbose_name='Telefono')),
                ('sex', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1, verbose_name='Sexo')),
                ('address', models.CharField(max_length=100, verbose_name='Direccion')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificacion')),
                ('last_session', models.DateTimeField(blank=True, editable=False, verbose_name='Ultima sesion')),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AppJuegos.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'historical Usuario',
                'verbose_name_plural': 'historical Usuarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
