# Generated by Django 4.1 on 2022-09-02 18:46

from django.db import migrations
from django.contrib.auth.hashers import make_password



class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0001_initial'),
    ]

    def insert_data(apps, schema_editor):
        Permission = apps.get_model('AppJuegos', 'Permission')
        Rol = apps.get_model('AppJuegos', 'Rol')
        User = apps.get_model('AppJuegos', 'User')
        RolPermission = apps.get_model('AppJuegos', 'RolPermission')

        user_create_permission = Permission(name='Crear Usuario')
        user_view_permission = Permission(name='Ver Usuario')
        user_edit_permission = Permission(name='Editar Usuario')
        user_delete_permission = Permission(name='Eliminar Usuario')

        rol_create_permission = Permission(name='Crear Rol')
        rol_view_permission = Permission(name='Ver Rol')
        rol_edit_permission = Permission(name='Editar Rol')
        rol_delete_permission = Permission(name='Eliminar Rol')

		# ==================================================================================================================
		#
		# Client permissions
        
        client_create_permission = Permission(name='Crear Cliente')
        client_view_permission = Permission(name='Ver Cliente')
        client_edit_permission = Permission(name='Editar Cliente')
        client_delete_permission = Permission(name='Eliminar Cliente')

		# ==================================================================================================================


        user_create_permission.save()
        user_view_permission.save()
        user_edit_permission.save()
        user_delete_permission.save()

        rol_create_permission.save()
        rol_view_permission.save()
        rol_edit_permission.save()
        rol_delete_permission.save()

		# ==================================================================================================================
                
        client_create_permission.save()
        client_view_permission.save()
        client_edit_permission.save()
        client_delete_permission.save()
        
		# ==================================================================================================================
        
        
        admin_rol = Rol(name='Administrador', description='Administrador del sistema')
        admin_rol.save()

        admin_user = User(
            username='admin',
            cedula='0000000000',
            names='Administrador',
            surnames='Sistema',
            email = 'admin@admin.com',
            password=make_password('admin'),
            phone='0000000000',
            sex='M',
            address='Administrador',
            rol= admin_rol
        )
        admin_user.save()

        RolPermission_1 =  RolPermission(rol_id=admin_rol.id, permission_id=user_create_permission.id)
        RolPermission_2 =  RolPermission(rol_id=admin_rol.id, permission_id=user_view_permission.id)
        RolPermission_3 =  RolPermission(rol_id=admin_rol.id, permission_id=user_edit_permission.id)
        RolPermission_4 =  RolPermission(rol_id=admin_rol.id, permission_id=user_delete_permission.id)
        RolPermission_5 =  RolPermission(rol_id=admin_rol.id, permission_id=rol_create_permission.id)
        RolPermission_6 =  RolPermission(rol_id=admin_rol.id, permission_id=rol_view_permission.id)
        RolPermission_7 =  RolPermission(rol_id=admin_rol.id, permission_id=rol_edit_permission.id)
        RolPermission_8 =  RolPermission(rol_id=admin_rol.id, permission_id=rol_delete_permission.id)
        
		# ==================================================================================================================
        
        RolPermission_9 =  RolPermission(rol_id=admin_rol.id, permission_id=client_create_permission.id)
        RolPermission_10 =  RolPermission(rol_id=admin_rol.id, permission_id=client_view_permission.id)
        RolPermission_11 =  RolPermission(rol_id=admin_rol.id, permission_id=client_edit_permission.id)
        RolPermission_12 =  RolPermission(rol_id=admin_rol.id, permission_id=client_delete_permission.id)

		# ==================================================================================================================
        
        
        RolPermission_1.save()
        RolPermission_2.save()
        RolPermission_3.save()
        RolPermission_4.save()
        RolPermission_5.save()
        RolPermission_6.save()
        RolPermission_7.save()
        RolPermission_8.save()
        
		# ==================================================================================================================        
        
        RolPermission_9.save()
        RolPermission_10.save()
        RolPermission_11.save()
        RolPermission_12.save()

		# ==================================================================================================================
    
    
    operations = [
        migrations.RunPython(insert_data),
    ]
