# Generated by Django 4.1.1 on 2022-10-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprobabilidad',
            name='winners_limit',
            field=models.PositiveIntegerField(verbose_name='winners_limit'),
        ),
        migrations.AlterField(
            model_name='probabilidad',
            name='winners_limit',
            field=models.PositiveIntegerField(verbose_name='winners_limit'),
        ),
    ]
