# Generated by Django 4.1 on 2022-09-02 18:46

from django.db import migrations

from AppJuegos.models import Permission


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0001_initial'),
    ]

    def insert_data(apps, schema_editor):
        Permission = apps.get_model('AppJuegos', 'Permission')

        user_create_permission = Permission(name='Crear Usuario')
        user_view_permission = Permission(name='Ver Usuario')
        user_edit_permission = Permission(name='Editar Usuario')
        user_delete_permission = Permission(name='Eliminar Usuario')

        rol_create_permission = Permission(name='Crear Rol')
        rol_view_permission = Permission(name='Ver Rol')
        rol_edit_permission = Permission(name='Editar Rol')
        rol_delete_permission = Permission(name='Eliminar Rol')

        user_create_permission.save()
        user_view_permission.save()
        user_edit_permission.save()
        user_delete_permission.save()

        rol_create_permission.save()
        rol_view_permission.save()
        rol_edit_permission.save()
        rol_delete_permission.save()

    operations = [
        migrations.RunPython(insert_data),
    ]
