# Generated by Django 4.1.1 on 2022-11-24 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0002_adminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='qr_code',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code/'),
        ),
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('color_text', models.CharField(choices=[('Black', 'black'), ('White', 'white'), ('Blue', 'blue'), ('Brown', 'brown'), ('Grey', 'grey'), ('Green', 'green'), ('Purple', 'purple'), ('Red', 'red'), ('Yellow', 'yellow')], max_length=50, null=True, verbose_name='color texto')),
                ('font_letter', models.CharField(choices=[('Arial', 'Arial'), ('Times New Roman', 'Times New Roman'), ('Helvetica', 'Helvetica'), ('Cambria', 'Cambria'), ('Century Gothic', 'Century Gothic'), ('Didot', 'Didot'), ('Bodoni', 'Bodoni'), ('Candara', 'Candara'), ('Optima', 'Optima'), ('Quicksand', 'Quicksand'), ('Courier New', 'Courier New'), ('Rockwell', 'Rockwell'), ('Copperplate', 'Copperplate')], max_length=50, null=True, verbose_name='Fuente Letra')),
                ('image_machine_game', models.ImageField(null=True, upload_to='design/', verbose_name='imagen maquina tragamonedas')),
                ('image_background_game', models.ImageField(null=True, upload_to='design/', verbose_name='imagen fondo juego')),
                ('image_logo_game', models.ImageField(null=True, upload_to='design/', verbose_name='imagen logo juego')),
                ('color_background_game', models.CharField(choices=[('Black', 'Black'), ('White', 'White')], default='Black', max_length=50, verbose_name='color de fondo')),
                ('video_screensaver', models.FileField(null=True, upload_to='screensaver/', verbose_name='video Salvapantallas')),
                ('video_autoplay', models.BooleanField(default=True, verbose_name='video autoplay')),
                ('video_loop', models.BooleanField(default=True, verbose_name='video loop')),
                ('title_button_screensaver', models.CharField(max_length=100, null=True, verbose_name='titulo boton salvapantallas')),
                ('scan_code_title', models.CharField(default='Escanear Codigo', max_length=200)),
                ('scan_code_description', models.CharField(default='Puedes escanear el codigo QR de tu ticket', max_length=200)),
                ('title_winner', models.CharField(default='White', max_length=150, null=True, verbose_name='titulo del ganador')),
                ('description_winner', models.CharField(max_length=200, null=True, verbose_name='descripcion ganador juego')),
                ('image_winner', models.FileField(null=True, upload_to='design/', verbose_name='imagen ganador')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJuegos.game', verbose_name='Juego')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalStyles',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('color_text', models.CharField(choices=[('Black', 'black'), ('White', 'white'), ('Blue', 'blue'), ('Brown', 'brown'), ('Grey', 'grey'), ('Green', 'green'), ('Purple', 'purple'), ('Red', 'red'), ('Yellow', 'yellow')], max_length=50, null=True, verbose_name='color texto')),
                ('font_letter', models.CharField(choices=[('Arial', 'Arial'), ('Times New Roman', 'Times New Roman'), ('Helvetica', 'Helvetica'), ('Cambria', 'Cambria'), ('Century Gothic', 'Century Gothic'), ('Didot', 'Didot'), ('Bodoni', 'Bodoni'), ('Candara', 'Candara'), ('Optima', 'Optima'), ('Quicksand', 'Quicksand'), ('Courier New', 'Courier New'), ('Rockwell', 'Rockwell'), ('Copperplate', 'Copperplate')], max_length=50, null=True, verbose_name='Fuente Letra')),
                ('image_machine_game', models.TextField(max_length=100, null=True, verbose_name='imagen maquina tragamonedas')),
                ('image_background_game', models.TextField(max_length=100, null=True, verbose_name='imagen fondo juego')),
                ('image_logo_game', models.TextField(max_length=100, null=True, verbose_name='imagen logo juego')),
                ('color_background_game', models.CharField(choices=[('Black', 'Black'), ('White', 'White')], default='Black', max_length=50, verbose_name='color de fondo')),
                ('video_screensaver', models.TextField(max_length=100, null=True, verbose_name='video Salvapantallas')),
                ('video_autoplay', models.BooleanField(default=True, verbose_name='video autoplay')),
                ('video_loop', models.BooleanField(default=True, verbose_name='video loop')),
                ('title_button_screensaver', models.CharField(max_length=100, null=True, verbose_name='titulo boton salvapantallas')),
                ('scan_code_title', models.CharField(default='Escanear Codigo', max_length=200)),
                ('scan_code_description', models.CharField(default='Puedes escanear el codigo QR de tu ticket', max_length=200)),
                ('title_winner', models.CharField(default='White', max_length=150, null=True, verbose_name='titulo del ganador')),
                ('description_winner', models.CharField(max_length=200, null=True, verbose_name='descripcion ganador juego')),
                ('image_winner', models.TextField(max_length=100, null=True, verbose_name='imagen ganador')),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_modified', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('game_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AppJuegos.game', verbose_name='Juego')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical styles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
