# Generated by Django 4.1.1 on 2022-11-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprobabilidad',
            name='attempts_limit',
            field=models.PositiveIntegerField(default=1, verbose_name='numero de intentos'),
        ),
        migrations.AddField(
            model_name='probabilidad',
            name='attempts_limit',
            field=models.PositiveIntegerField(default=1, verbose_name='numero de intentos'),
        ),
    ]
