# Generated by Django 4.1.1 on 2022-10-07 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0002_auto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpremios',
            name='cedula_modify',
        ),
        migrations.RemoveField(
            model_name='historicalpremios',
            name='cedula_register',
        ),
        migrations.RemoveField(
            model_name='premios',
            name='cedula_modify',
        ),
        migrations.RemoveField(
            model_name='premios',
            name='cedula_register',
        ),
        migrations.AlterField(
            model_name='historicalpremios',
            name='user_modify',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modifica'),
        ),
        migrations.AlterField(
            model_name='historicalpremios',
            name='user_register',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registra'),
        ),
        migrations.AlterField(
            model_name='premios',
            name='user_modify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_modify', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modifica'),
        ),
        migrations.AlterField(
            model_name='premios',
            name='user_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_register', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registra'),
        ),
    ]
