# Generated by Django 4.1.1 on 2022-10-05 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0002_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(max_length=100, verbose_name='Descripcion')),
                ('image', models.ImageField(upload_to='premios/', verbose_name='Imagen')),
                ('initial_stock', models.IntegerField(verbose_name='Stock inicial')),
                ('current_stock', models.IntegerField(default=models.IntegerField(verbose_name='Stock inicial'), verbose_name='Stock actual')),
                ('prizes_awarded', models.IntegerField(default=0, verbose_name='Premios entregados')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('is_active', models.BooleanField(default=True)),
                ('cedula_register', models.CharField(max_length=10, verbose_name='Cédula')),
                ('user_register', models.CharField(max_length=255, verbose_name='Usuario que registro')),
                ('cedula_modify', models.CharField(default=models.CharField(max_length=10, verbose_name='Cédula'), max_length=10, verbose_name='Cédula')),
                ('user_modify', models.CharField(default=models.CharField(max_length=255, verbose_name='Usuario que registro'), max_length=255, verbose_name='Usuario que modifico')),
                ('category', models.CharField(choices=[('L', 'Legendaria'), ('E', 'Epica'), ('R', 'Rara'), ('C', 'Comun')], default='C', max_length=1, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Premio',
                'verbose_name_plural': 'Premios',
                'ordering': ['id', 'name', 'description', 'initial_stock', 'current_stock', 'prizes_awarded'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPremios',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(max_length=100, verbose_name='Descripcion')),
                ('image', models.TextField(max_length=100, verbose_name='Imagen')),
                ('initial_stock', models.IntegerField(verbose_name='Stock inicial')),
                ('current_stock', models.IntegerField(default=models.IntegerField(verbose_name='Stock inicial'), verbose_name='Stock actual')),
                ('prizes_awarded', models.IntegerField(default=0, verbose_name='Premios entregados')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificacion')),
                ('is_active', models.BooleanField(default=True)),
                ('cedula_register', models.CharField(max_length=10, verbose_name='Cédula')),
                ('user_register', models.CharField(max_length=255, verbose_name='Usuario que registro')),
                ('cedula_modify', models.CharField(default=models.CharField(max_length=10, verbose_name='Cédula'), max_length=10, verbose_name='Cédula')),
                ('user_modify', models.CharField(default=models.CharField(max_length=255, verbose_name='Usuario que registro'), max_length=255, verbose_name='Usuario que modifico')),
                ('category', models.CharField(choices=[('L', 'Legendaria'), ('E', 'Epica'), ('R', 'Rara'), ('C', 'Comun')], default='C', max_length=1, verbose_name='Categoria')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Premio',
                'verbose_name_plural': 'historical Premios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
