# Generated by Django 4.1.1 on 2022-10-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0002_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(choices=[('Ninguno', 'Ninguno'), ('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Deshabilitado', 'Desabilitado')], default='Ninguno', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='state',
            field=models.CharField(choices=[('Ninguno', 'Ninguno'), ('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Deshabilitado', 'Desabilitado')], default='Ninguno', max_length=100, verbose_name='Estado'),
        ),
    ]
