# Generated by Django 4.1.1 on 2022-12-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0002_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='invoice_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='invoice_number',
            field=models.CharField(max_length=255),
        ),
    ]
