# Generated by Django 4.1.1 on 2022-11-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppJuegos", "0002_adminuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalticket",
            name="qr_code",
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="qr_code",
            field=models.ImageField(blank=True, upload_to="qr_code/"),
        ),
    ]
