# Generated by Django 4.1.1 on 2023-01-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.IntegerField(default=0, verbose_name='Jugadores'),
        ),
        migrations.AddField(
            model_name='historicalgame',
            name='players',
            field=models.IntegerField(default=0, verbose_name='Jugadores'),
        ),
    ]
