# Generated by Django 4.1.1 on 2022-11-23 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0002_adminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='qr_code',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_code/'),
        ),
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('video_screensaver', models.FileField(null=True, upload_to='screensaver/', verbose_name='video Salvapantallas')),
                ('title_button_screensaver', models.CharField(max_length=100, null=True, verbose_name='titulo boton salvapantallas')),
                ('image_background_game', models.ImageField(null=True, upload_to='design/', verbose_name='imagen fondo juego')),
                ('image_logo_game', models.ImageField(null=True, upload_to='design/', verbose_name='imagen logo juego')),
                ('color_background_game', models.ImageField(null=True, upload_to='design/', verbose_name='color fondo juego')),
                ('color_text', models.CharField(max_length=50, null=True, verbose_name='color texto')),
                ('title_winner', models.CharField(max_length=150, null=True, verbose_name='titulo del ganador')),
                ('description_winner', models.CharField(max_length=200, null=True, verbose_name='descripcion ganador juego')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJuegos.game', verbose_name='Juego')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalStyles',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('video_screensaver', models.TextField(max_length=100, null=True, verbose_name='video Salvapantallas')),
                ('title_button_screensaver', models.CharField(max_length=100, null=True, verbose_name='titulo boton salvapantallas')),
                ('image_background_game', models.TextField(max_length=100, null=True, verbose_name='imagen fondo juego')),
                ('image_logo_game', models.TextField(max_length=100, null=True, verbose_name='imagen logo juego')),
                ('color_background_game', models.TextField(max_length=100, null=True, verbose_name='color fondo juego')),
                ('color_text', models.CharField(max_length=50, null=True, verbose_name='color texto')),
                ('title_winner', models.CharField(max_length=150, null=True, verbose_name='titulo del ganador')),
                ('description_winner', models.CharField(max_length=200, null=True, verbose_name='descripcion ganador juego')),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_modified', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('game_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AppJuegos.game', verbose_name='Juego')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical styles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
