# Generated by Django 4.1.1 on 2022-10-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0002_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de fin')),
                ('juego', models.CharField(choices=[('T', 'Traga Monedas')], default='T', max_length=1, verbose_name='Juego')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
