# Generated by Django 4.1.1 on 2022-12-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0002_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpublicity',
            name='created',
        ),
        migrations.RemoveField(
            model_name='historicalpublicity',
            name='image',
        ),
        migrations.RemoveField(
            model_name='historicalpublicity',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='historicalpublicity',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='publicity',
            name='created',
        ),
        migrations.RemoveField(
            model_name='publicity',
            name='image',
        ),
        migrations.RemoveField(
            model_name='publicity',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='publicity',
            name='titulo',
        ),
        migrations.AddField(
            model_name='historicalpublicity',
            name='time_display',
            field=models.IntegerField(default=4, verbose_name='Tiempo de vista '),
        ),
        migrations.AddField(
            model_name='publicity',
            name='time_display',
            field=models.IntegerField(default=4, verbose_name='Tiempo de vista '),
        ),
    ]
