# Generated by Django 4.1.1 on 2022-12-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0002_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalticket',
            old_name='date_modified',
            new_name='date_ticket_played',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='date_modified',
            new_name='date_ticket_played',
        ),
        migrations.RemoveField(
            model_name='historicalticket',
            name='qr_code_url',
        ),
        migrations.RemoveField(
            model_name='historicalticket',
            name='user_modifier',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='qr_code_url',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user_modifier',
        ),
    ]
