# Generated by Django 4.1.1 on 2022-11-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppJuegos", "0002_adminuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="name",
            field=models.CharField(
                choices=[("Tragamonedas", "Tragamonedas")],
                default="Tragamonedas",
                max_length=50,
                verbose_name="Nombre",
            ),
        ),
        migrations.AddField(
            model_name="historicalgame",
            name="name",
            field=models.CharField(
                choices=[("Tragamonedas", "Tragamonedas")],
                default="Tragamonedas",
                max_length=50,
                verbose_name="Nombre",
            ),
        ),
    ]
