# Generated by Django 4.1.1 on 2022-10-26 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0002_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='publicidad/', verbose_name='Imagen publicidad')),
                ('titulo', models.CharField(max_length=100, verbose_name='winners_limit')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de modificacion')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Publicity',
                'verbose_name_plural': 'Publicities',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPublicity',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('image', models.TextField(max_length=100, verbose_name='Imagen publicidad')),
                ('titulo', models.CharField(max_length=100, verbose_name='winners_limit')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de modificacion')),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Publicity',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
