# Generated by Django 4.1.1 on 2022-10-19 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0002_auto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user_modify',
            new_name='user_client_modify',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='user_register',
            new_name='user_client_register',
        ),
        migrations.RenameField(
            model_name='historicalclient',
            old_name='user_modify',
            new_name='user_client_modify',
        ),
        migrations.RenameField(
            model_name='historicalclient',
            old_name='user_register',
            new_name='user_client_register',
        ),
    ]
