# Generated by Django 4.1.1 on 2023-01-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppJuegos", "0002_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("audio", models.FileField(upload_to="audio/", verbose_name="audio")),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="players",
            field=models.IntegerField(default=0, verbose_name="Jugadores"),
        ),
        migrations.AddField(
            model_name="historicalgame",
            name="players",
            field=models.IntegerField(default=0, verbose_name="Jugadores"),
        ),
        migrations.AlterField(
            model_name="award",
            name="category",
            field=models.CharField(
                choices=[
                    ("Legendaria", "Legendaria"),
                    ("Épica", "Épica"),
                    ("Rara", "Rara"),
                    ("Común", "Común"),
                ],
                default="Comun",
                max_length=50,
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="sex",
            field=models.CharField(
                choices=[
                    ("Masculino", "Masculino"),
                    ("Femenino", "Femenino"),
                    ("Otro", "Otro"),
                ],
                default="Femenino",
                max_length=50,
                verbose_name="Sexo",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaward",
            name="category",
            field=models.CharField(
                choices=[
                    ("Legendaria", "Legendaria"),
                    ("Épica", "Épica"),
                    ("Rara", "Rara"),
                    ("Común", "Común"),
                ],
                default="Comun",
                max_length=50,
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="sex",
            field=models.CharField(
                choices=[
                    ("Masculino", "Masculino"),
                    ("Femenino", "Femenino"),
                    ("Otro", "Otro"),
                ],
                default="Femenino",
                max_length=50,
                verbose_name="Sexo",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="sex",
            field=models.CharField(
                choices=[
                    ("Masculino", "Masculino"),
                    ("Femenino", "Femenino"),
                    ("Otro", "Otro"),
                ],
                default="Masculino",
                max_length=50,
                verbose_name="Sexo",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(
                choices=[
                    ("Masculino", "Masculino"),
                    ("Femenino", "Femenino"),
                    ("Otro", "Otro"),
                ],
                default="Masculino",
                max_length=50,
                verbose_name="Sexo",
            ),
        ),
    ]
