# Generated by Django 4.1.1 on 2022-11-30 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0002_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprobabilidad',
            name='porcent_win',
        ),
        migrations.RemoveField(
            model_name='probabilidad',
            name='porcent_win',
        ),
        migrations.AddField(
            model_name='historicalmatch',
            name='award',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AppJuegos.award'),
        ),
        migrations.AddField(
            model_name='historicalmatch',
            name='win_match',
            field=models.BooleanField(default=False, verbose_name='gano la partida?'),
        ),
        migrations.AddField(
            model_name='historicalprobabilidad',
            name='percent_win',
            field=models.PositiveIntegerField(default=20, verbose_name='porcent_win'),
        ),
        migrations.AddField(
            model_name='match',
            name='award',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='award', to='AppJuegos.award'),
        ),
        migrations.AddField(
            model_name='match',
            name='win_match',
            field=models.BooleanField(default=False, verbose_name='gano la partida?'),
        ),
        migrations.AddField(
            model_name='probabilidad',
            name='percent_win',
            field=models.PositiveIntegerField(default=20, verbose_name='porcent_win'),
        ),
        migrations.AlterField(
            model_name='historicalstyles',
            name='description_winner',
            field=models.CharField(default='HAS GANADO!', max_length=200, null=True, verbose_name='descripcion ganador juego'),
        ),
        migrations.AlterField(
            model_name='historicalstyles',
            name='title_winner',
            field=models.CharField(default='JUEGA OTRA VEZ!', max_length=150, null=True, verbose_name='titulo del ganador'),
        ),
        migrations.AlterField(
            model_name='styles',
            name='description_winner',
            field=models.CharField(default='HAS GANADO!', max_length=200, null=True, verbose_name='descripcion ganador juego'),
        ),
        migrations.AlterField(
            model_name='styles',
            name='title_winner',
            field=models.CharField(default='JUEGA OTRA VEZ!', max_length=150, null=True, verbose_name='titulo del ganador'),
        ),
    ]
