# Generated by Django 4.1.1 on 2022-11-03 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0002_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardgame',
            name='premio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_in_game', to='AppJuegos.award', verbose_name='Premio'),
        ),
    ]
