# Generated by Django 4.1.1 on 2022-09-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0002_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
