# Generated by Django 4.1.1 on 2022-12-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppJuegos", "0002_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicity_bottom",
            name="time_display",
            field=models.IntegerField(default=3, null=True),
        ),
        migrations.AddField(
            model_name="publicity_top",
            name="time_display",
            field=models.IntegerField(default=3, null=True),
        ),
    ]
