# Generated by Django 4.1.1 on 2022-11-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0002_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ['id', 'name', 'description', 'initial_stock', 'prizes_awarded'], 'verbose_name': 'Premio', 'verbose_name_plural': 'Premios'},
        ),
        migrations.RemoveField(
            model_name='award',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='historicalaward',
            name='current_stock',
        ),
        migrations.AddField(
            model_name='award',
            name='condition_stock',
            field=models.IntegerField(default=0, verbose_name='Stock Condicionado'),
        ),
        migrations.AddField(
            model_name='historicalaward',
            name='condition_stock',
            field=models.IntegerField(default=0, verbose_name='Stock Condicionado'),
        ),
    ]
