# Generated by Django 4.1.1 on 2022-10-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0003_rename_user_modify_client_user_client_modify_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(choices=[('NO', 'Ninguno'), ('AC', 'Activo'), ('IN', 'Inactivo'), ('DI', 'Desabilitado')], default='NO', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='state',
            field=models.CharField(choices=[('NO', 'Ninguno'), ('AC', 'Activo'), ('IN', 'Inactivo'), ('DI', 'Desabilitado')], default='NO', max_length=2, verbose_name='Estado'),
        ),
    ]
