# Generated by Django 4.1.1 on 2022-12-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0003_rename_date_modified_historicalticket_date_ticket_played_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('logo', models.ImageField(null=True, upload_to='logo_ticket/')),
                ('title', models.CharField(default='Gana premios jugando', max_length=255, null=True)),
                ('description', models.CharField(default='Gana premios jugando', max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='state',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Reclamado', 'Reclamado')], default='Disponible', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Reclamado', 'Reclamado')], default='Disponible', max_length=100),
        ),
    ]
