# Generated by Django 4.1.1 on 2023-01-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0003_game_players_historicalgame_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='category',
            field=models.CharField(choices=[('Legendaria', 'Legendaria'), ('Épica', 'Épica'), ('Rara', 'Rara'), ('ComÚn', 'ComÉn')], default='Comun', max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='historicalaward',
            name='category',
            field=models.CharField(choices=[('Legendaria', 'Legendaria'), ('Épica', 'Épica'), ('Rara', 'Rara'), ('ComÚn', 'ComÉn')], default='Comun', max_length=50, verbose_name='Categoria'),
        ),
    ]
