# Generated by Django 4.1.1 on 2022-11-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppJuegos", "0003_alter_historicalticket_qr_code_alter_ticket_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalticket",
            name="qr_code",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_code/"),
        ),
    ]
