# Generated by Django 4.1.1 on 2022-12-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0003_remove_historicalprobabilidad_porcent_win_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpublicity',
            name='image',
            field=models.TextField(max_length=100, verbose_name='Imagen_publicidad'),
        ),
        migrations.AlterField(
            model_name='publicity',
            name='image',
            field=models.ImageField(upload_to='publicidad/', verbose_name='Imagen_publicidad'),
        ),
    ]
