# Generated by Django 4.1.1 on 2022-10-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0003_publicity_historicalpublicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpublicity',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='titulo publicidad'),
        ),
        migrations.AlterField(
            model_name='publicity',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='titulo publicidad'),
        ),
    ]
