# Generated by Django 4.1.1 on 2022-11-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0003_alter_awardgame_premio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Fecha fin juego'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game',
            field=models.CharField(choices=[('T', 'Traga Monedas')], default='T', max_length=1, unique=True, verbose_name='Juego'),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Fecha inicio juego'),
        ),
        migrations.AlterField(
            model_name='historicalgame',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Fecha fin juego'),
        ),
        migrations.AlterField(
            model_name='historicalgame',
            name='game',
            field=models.CharField(choices=[('T', 'Traga Monedas')], db_index=True, default='T', max_length=1, verbose_name='Juego'),
        ),
        migrations.AlterField(
            model_name='historicalgame',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Fecha inicio juego'),
        ),
    ]
