# Generated by Django 4.1.1 on 2022-11-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppJuegos", "0003_game_name_historicalgame_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="description",
            field=models.TextField(
                default="", max_length=100, verbose_name="Descripción"
            ),
        ),
        migrations.AddField(
            model_name="historicalgame",
            name="description",
            field=models.TextField(
                default="", max_length=100, verbose_name="Descripción"
            ),
        ),
    ]
