# Generated by Django 4.1.1 on 2022-11-16 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0003_game_name_historicalgame_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardgame',
            name='premio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_in_game', to='AppJuegos.award', verbose_name='Premio'),
        ),
        migrations.AlterField(
            model_name='game',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Fecha fin juego'),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Fecha inicio juego'),
        ),
        migrations.AlterField(
            model_name='historicalgame',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Fecha fin juego'),
        ),
        migrations.AlterField(
            model_name='historicalgame',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Fecha inicio juego'),
        ),
    ]
