# Generated by Django 4.1.1 on 2022-10-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0003_premios_historicalpremios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpremios',
            name='cedula_modify',
            field=models.CharField(default='----------', max_length=10, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='historicalpremios',
            name='current_stock',
            field=models.IntegerField(default=0, verbose_name='Stock actual'),
        ),
        migrations.AlterField(
            model_name='historicalpremios',
            name='user_modify',
            field=models.CharField(default='Sin modificar', max_length=255, verbose_name='Usuario que modifico'),
        ),
        migrations.AlterField(
            model_name='premios',
            name='cedula_modify',
            field=models.CharField(default='----------', max_length=10, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='premios',
            name='current_stock',
            field=models.IntegerField(default=0, verbose_name='Stock actual'),
        ),
        migrations.AlterField(
            model_name='premios',
            name='user_modify',
            field=models.CharField(default='Sin modificar', max_length=255, verbose_name='Usuario que modifico'),
        ),
    ]
