# Generated by Django 4.1.1 on 2022-11-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0003_historicalprobabilidad_attempts_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprobabilidad',
            name='porcent_win',
            field=models.PositiveIntegerField(default=20, verbose_name='porcent_win'),
        ),
        migrations.AlterField(
            model_name='historicalprobabilidad',
            name='winners_limit',
            field=models.PositiveIntegerField(default=1, verbose_name='winners_limit'),
        ),
        migrations.AlterField(
            model_name='probabilidad',
            name='porcent_win',
            field=models.PositiveIntegerField(default=20, verbose_name='porcent_win'),
        ),
        migrations.AlterField(
            model_name='probabilidad',
            name='winners_limit',
            field=models.PositiveIntegerField(default=1, verbose_name='winners_limit'),
        ),
    ]
