# Generated by Django 4.1.1 on 2022-11-19 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AppJuegos", "0004_game_description_historicalgame_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="state",
            field=models.CharField(
                choices=[("Activado", "Activado"), ("Desactivado", "Desactivado")],
                default="Desactivado",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="historicalgame",
            name="state",
            field=models.CharField(
                choices=[("Activado", "Activado"), ("Desactivado", "Desactivado")],
                default="Desactivado",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="awardgame",
            name="premio_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="award_in_game",
                to="AppJuegos.award",
                verbose_name="Premio",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="description",
            field=models.TextField(
                default="Descripción", max_length=100, verbose_name="Descripción"
            ),
        ),
        migrations.AlterField(
            model_name="historicalgame",
            name="description",
            field=models.TextField(
                default="Descripción", max_length=100, verbose_name="Descripción"
            ),
        ),
    ]
