# Generated by Django 4.1.1 on 2024-06-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0004_alter_game_name_alter_historicalgame_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(choices=[('Tragamonedas', 'Tragamonedas'), ('Precision', 'Precision'), ('Dados', 'Dados'), ('Puertas', 'Puertas')], default='Tragamonedas', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicalgame',
            name='name',
            field=models.CharField(choices=[('Tragamonedas', 'Tragamonedas'), ('Precision', 'Precision'), ('Dados', 'Dados'), ('Puertas', 'Puertas')], default='Tragamonedas', max_length=50, verbose_name='Nombre'),
        ),
    ]
