# Generated by Django 4.1.1 on 2022-12-31 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0004_alter_match_award'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='state',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='state',
        ),
    ]
