# Generated by Django 4.1.1 on 2022-11-19 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0004_alter_awardgame_premio_id_alter_game_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('video_screensaver', models.FileField(upload_to='screensaver/')),
                ('title_button_screensaver', models.CharField(max_length=100)),
                ('image_background_game', models.ImageField(upload_to='design/')),
                ('image_logo_game', models.ImageField(upload_to='design/')),
                ('color_background_game', models.ImageField(upload_to='design/')),
                ('color_text', models.CharField(max_length=50)),
                ('title_winner', models.CharField(max_length=150)),
                ('description_winner', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJuegos.game', verbose_name='Juego')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalStyles',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('video_screensaver', models.TextField(max_length=100)),
                ('title_button_screensaver', models.CharField(max_length=100)),
                ('image_background_game', models.TextField(max_length=100)),
                ('image_logo_game', models.TextField(max_length=100)),
                ('color_background_game', models.TextField(max_length=100)),
                ('color_text', models.CharField(max_length=50)),
                ('title_winner', models.CharField(max_length=150)),
                ('description_winner', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_modified', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('game_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AppJuegos.game', verbose_name='Juego')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical styles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
