# Generated by Django 4.1.1 on 2022-11-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0004_alter_game_end_date_alter_game_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game',
            field=models.CharField(choices=[('T', 'Traga Monedas')], default='T', max_length=1, verbose_name='Juego'),
        ),
        migrations.AlterField(
            model_name='historicalgame',
            name='game',
            field=models.CharField(choices=[('T', 'Traga Monedas')], default='T', max_length=1, verbose_name='Juego'),
        ),
    ]
