# Generated by Django 4.1.1 on 2022-11-28 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0004_alter_historicalprobabilidad_porcent_win_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprobabilidad',
            name='user_modify',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modifica'),
        ),
        migrations.AddField(
            model_name='historicalprobabilidad',
            name='user_register',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registra'),
        ),
        migrations.AddField(
            model_name='probabilidad',
            name='user_modify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_modify_probabilidad', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modifica'),
        ),
        migrations.AddField(
            model_name='probabilidad',
            name='user_register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_register_probabilidad', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registra'),
        ),
    ]
