# Generated by Django 4.1.1 on 2022-10-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0004_alter_historicalpremios_cedula_modify_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesJuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_juegos/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'ImagenJuego',
                'verbose_name_plural': 'ImagenesJuegos',
                'ordering': ['imagen'],
            },
        ),
    ]
