# Generated by Django 4.1.1 on 2023-01-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0004_alter_award_category_alter_historicalaward_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='category',
            field=models.CharField(choices=[('Legendaria', 'Legendaria'), ('Épica', 'Épica'), ('Rara', 'Rara'), ('Común', 'Común')], default='Comun', max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='historicalaward',
            name='category',
            field=models.CharField(choices=[('Legendaria', 'Legendaria'), ('Épica', 'Épica'), ('Rara', 'Rara'), ('Común', 'Común')], default='Comun', max_length=50, verbose_name='Categoria'),
        ),
    ]
