# Generated by Django 4.1.1 on 2022-12-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0004_alter_historicalpublicity_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpublicity',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='publicity',
            old_name='image',
            new_name='imagen',
        ),
    ]
