# Generated by Django 4.1.1 on 2022-10-27 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0004_alter_historicalpublicity_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardgame',
            name='premio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_in_game', to='AppJuegos.award', unique=True, verbose_name='Premio'),
        ),
    ]
