# Generated by Django 4.1.1 on 2022-10-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0004_alter_historicalpremios_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpremios',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='premios',
            old_name='image',
            new_name='imagen',
        ),
    ]
