# Generated by Django 4.1.1 on 2022-11-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0005_styles_historicalstyles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstyles',
            name='color_background_game',
            field=models.TextField(max_length=100, verbose_name='color fondo juego'),
        ),
        migrations.AlterField(
            model_name='historicalstyles',
            name='color_text',
            field=models.CharField(max_length=50, verbose_name='color texto'),
        ),
        migrations.AlterField(
            model_name='historicalstyles',
            name='description_winner',
            field=models.CharField(max_length=200, verbose_name='descripcion ganador juego'),
        ),
        migrations.AlterField(
            model_name='historicalstyles',
            name='image_background_game',
            field=models.TextField(max_length=100, verbose_name='imagen fondo juego'),
        ),
        migrations.AlterField(
            model_name='historicalstyles',
            name='image_logo_game',
            field=models.TextField(max_length=100, verbose_name='imagen logo juego'),
        ),
        migrations.AlterField(
            model_name='historicalstyles',
            name='title_button_screensaver',
            field=models.CharField(max_length=100, verbose_name='titulo boton salvapantallas'),
        ),
        migrations.AlterField(
            model_name='historicalstyles',
            name='title_winner',
            field=models.CharField(max_length=150, verbose_name='titulo del ganador'),
        ),
        migrations.AlterField(
            model_name='historicalstyles',
            name='video_screensaver',
            field=models.TextField(max_length=100, null=True, verbose_name='video Salvapantallas'),
        ),
        migrations.AlterField(
            model_name='styles',
            name='color_background_game',
            field=models.ImageField(upload_to='design/', verbose_name='color fondo juego'),
        ),
        migrations.AlterField(
            model_name='styles',
            name='color_text',
            field=models.CharField(max_length=50, verbose_name='color texto'),
        ),
        migrations.AlterField(
            model_name='styles',
            name='description_winner',
            field=models.CharField(max_length=200, verbose_name='descripcion ganador juego'),
        ),
        migrations.AlterField(
            model_name='styles',
            name='image_background_game',
            field=models.ImageField(upload_to='design/', verbose_name='imagen fondo juego'),
        ),
        migrations.AlterField(
            model_name='styles',
            name='image_logo_game',
            field=models.ImageField(upload_to='design/', verbose_name='imagen logo juego'),
        ),
        migrations.AlterField(
            model_name='styles',
            name='title_button_screensaver',
            field=models.CharField(max_length=100, verbose_name='titulo boton salvapantallas'),
        ),
        migrations.AlterField(
            model_name='styles',
            name='title_winner',
            field=models.CharField(max_length=150, verbose_name='titulo del ganador'),
        ),
        migrations.AlterField(
            model_name='styles',
            name='video_screensaver',
            field=models.FileField(null=True, upload_to='screensaver/', verbose_name='video Salvapantallas'),
        ),
    ]
