# Generated by Django 4.1.1 on 2022-10-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0005_imagenesjuegos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesjuegos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
