# Generated by Django 4.1.1 on 2022-10-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0005_rename_image_historicalpremios_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpremios',
            name='juego',
            field=models.CharField(choices=[('T', 'Traga Monedas')], default='T', max_length=1, verbose_name='Juego'),
        ),
        migrations.AddField(
            model_name='premios',
            name='juego',
            field=models.CharField(choices=[('T', 'Traga Monedas')], default='T', max_length=1, verbose_name='Juego'),
        ),
        migrations.AlterField(
            model_name='historicalpremios',
            name='category',
            field=models.CharField(choices=[('L', 'Legendaria'), ('E', 'Epica'), ('R', 'Rara'), ('C', 'Comun'), ('P', 'Publicidad')], default='C', max_length=1, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='premios',
            name='category',
            field=models.CharField(choices=[('L', 'Legendaria'), ('E', 'Epica'), ('R', 'Rara'), ('C', 'Comun'), ('P', 'Publicidad')], default='C', max_length=1, verbose_name='Categoria'),
        ),
    ]
