# Generated by Django 4.1.1 on 2022-11-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0005_historicalprobabilidad_user_modify_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprobabilidad',
            name='user_modify',
        ),
        migrations.RemoveField(
            model_name='historicalprobabilidad',
            name='user_register',
        ),
        migrations.RemoveField(
            model_name='probabilidad',
            name='user_modify',
        ),
        migrations.RemoveField(
            model_name='probabilidad',
            name='user_register',
        ),
    ]
