# Generated by Django 4.1.1 on 2022-12-01 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0005_rename_image_historicalpublicity_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpublicity',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='publicity',
            old_name='imagen',
            new_name='image',
        ),
    ]
