# Generated by Django 4.1.1 on 2024-07-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0006_gamecurrentsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('image_type', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='game_images/')),
            ],
        ),
    ]
