# Generated by Django 4.1.1 on 2022-11-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0006_game_players_historicalgame_players'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awardcondition',
            options={'ordering': ['id', 'award', 'game'], 'verbose_name': 'CondicionPremio', 'verbose_name_plural': 'CondicionPremios'},
        ),
        migrations.RemoveField(
            model_name='awardcondition',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='awardcondition',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historicalawardcondition',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='historicalawardcondition',
            name='is_active',
        ),
        migrations.AddField(
            model_name='awardcondition',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalawardcondition',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
