# Generated by Django 4.1.1 on 2022-11-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppJuegos", "0006_remove_historicalprobabilidad_user_modify_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalticket",
            old_name="qr_code",
            new_name="qr_code_url",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="qr_code",
            new_name="qr_code_url",
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="qr_code_digits",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ticket",
            name="qr_code_digits",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
