# Generated by Django 4.1.1 on 2022-10-10 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0006_historicalpremios_juego_premios_juego_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('names', models.CharField(max_length=100, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo Electronico')),
                ('phone', models.CharField(max_length=10, verbose_name='Telefono')),
                ('sex', models.CharField(choices=[('N', 'Ninguno'), ('F', 'Femenino'), ('M', 'Masculino')], default='N', max_length=1, verbose_name='Sexo')),
                ('address', models.CharField(max_length=500, verbose_name='Direccion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('state', models.CharField(choices=[('NO', 'None'), ('AC', 'Active'), ('IN', 'Inactive'), ('DI', 'Disabled')], default='N', max_length=2, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id', 'cedula', 'names', 'surnames', 'email', 'phone'],
            },
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='sex',
            field=models.CharField(choices=[('N', 'Ninguno'), ('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('N', 'Ninguno'), ('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1, verbose_name='Sexo'),
        ),
        migrations.CreateModel(
            name='HistoricalClient',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('cedula', models.CharField(db_index=True, max_length=10, verbose_name='Cédula')),
                ('names', models.CharField(max_length=100, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(db_index=True, max_length=100, verbose_name='Correo Electronico')),
                ('phone', models.CharField(max_length=10, verbose_name='Telefono')),
                ('sex', models.CharField(choices=[('N', 'Ninguno'), ('F', 'Femenino'), ('M', 'Masculino')], default='N', max_length=1, verbose_name='Sexo')),
                ('address', models.CharField(max_length=500, verbose_name='Direccion')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificacion')),
                ('state', models.CharField(choices=[('NO', 'None'), ('AC', 'Active'), ('IN', 'Inactive'), ('DI', 'Disabled')], default='N', max_length=2, verbose_name='Estado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cliente',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
