# Generated by Django 4.1.1 on 2022-11-30 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0007_rename_qr_code_historicalticket_qr_code_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatch',
            name='award',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AppJuegos.award'),
        ),
        migrations.AddField(
            model_name='historicalmatch',
            name='win_match',
            field=models.BooleanField(default=False, verbose_name='gano la partida?'),
        ),
        migrations.AddField(
            model_name='match',
            name='award',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='award', to='AppJuegos.award'),
        ),
        migrations.AddField(
            model_name='match',
            name='win_match',
            field=models.BooleanField(default=False, verbose_name='gano la partida?'),
        ),
    ]
