# Generated by Django 4.1.1 on 2022-11-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppJuegos", "0007_alter_awardcondition_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="award",
            name="juego",
            field=models.CharField(
                choices=[("T", "Tragamonedas")],
                default="T",
                max_length=1,
                verbose_name="Juego",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="game",
            field=models.CharField(
                choices=[("T", "Tragamonedas")],
                default="T",
                max_length=1,
                verbose_name="Juego",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaward",
            name="juego",
            field=models.CharField(
                choices=[("T", "Tragamonedas")],
                default="T",
                max_length=1,
                verbose_name="Juego",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgame",
            name="game",
            field=models.CharField(
                choices=[("T", "Tragamonedas")],
                default="T",
                max_length=1,
                verbose_name="Juego",
            ),
        ),
    ]
