# Generated by Django 4.1.1 on 2022-10-16 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AppJuegos", "0007_client_alter_historicaluser_sex_alter_user_sex_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalpremios",
            old_name="user_modify",
            new_name="user_client_modify",
        ),
        migrations.RenameField(
            model_name="historicalpremios",
            old_name="user_register",
            new_name="user_client_register",
        ),
        migrations.RemoveField(
            model_name="premios",
            name="user_modify",
        ),
        migrations.RemoveField(
            model_name="premios",
            name="user_register",
        ),
        migrations.AddField(
            model_name="premios",
            name="user_client_modify",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_client_modify",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario que modifica",
            ),
        ),
        migrations.AddField(
            model_name="premios",
            name="user_client_register",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_client_register",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario que registra",
            ),
            preserve_default=False,
        ),
    ]
