# Generated by Django 4.1.1 on 2024-07-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0007_gameimageupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameimageupload',
            name='image',
            field=models.ImageField(upload_to='img/<django.db.models.fields.CharField>/'),
        ),
    ]
