# Generated by Django 4.1.1 on 2022-11-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppJuegos", "0008_alter_award_juego_alter_game_game_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalticket",
            name="qr_code",
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="qr_code",
            field=models.ImageField(blank=True, upload_to="qr_code"),
        ),
    ]
