# Generated by Django 4.1.1 on 2022-10-16 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "AppJuegos",
            "0008_rename_user_modify_historicalpremios_user_client_modify_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalpremios",
            old_name="user_client_modify",
            new_name="user_modify",
        ),
        migrations.RenameField(
            model_name="historicalpremios",
            old_name="user_client_register",
            new_name="user_register",
        ),
        migrations.RemoveField(
            model_name="premios",
            name="user_client_modify",
        ),
        migrations.RemoveField(
            model_name="premios",
            name="user_client_register",
        ),
        migrations.AddField(
            model_name="client",
            name="user_client_modify",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_client_modify",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario que modifica",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="user_client_register",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_client_register",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario que registra",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="user_client_modify",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario que modifica",
            ),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="user_client_register",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario que registra",
            ),
        ),
        migrations.AddField(
            model_name="premios",
            name="user_modify",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_modify",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario que modifica",
            ),
        ),
        migrations.AddField(
            model_name="premios",
            name="user_register",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_register",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario que registra",
            ),
            preserve_default=False,
        ),
    ]
