# Generated by Django 4.1.1 on 2022-10-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "AppJuegos",
            "0009_rename_user_client_modify_historicalpremios_user_modify_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="state",
            field=models.CharField(
                choices=[
                    ("NO", "Ninguno"),
                    ("AC", "Activo"),
                    ("IN", "Inactivo"),
                    ("DI", "Desabilitado"),
                ],
                default="N",
                max_length=2,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="state",
            field=models.CharField(
                choices=[
                    ("NO", "Ninguno"),
                    ("AC", "Activo"),
                    ("IN", "Inactivo"),
                    ("DI", "Desabilitado"),
                ],
                default="N",
                max_length=2,
                verbose_name="Estado",
            ),
        ),
    ]
