# Generated by Django 4.1.1 on 2022-11-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppJuegos", "0010_alter_ticket_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="qr_code",
            field=models.ImageField(blank=True, upload_to="qr_code/"),
        ),
    ]
