# Generated by Django 4.1.1 on 2024-08-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0010_alter_game_name_alter_historicalgame_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='styles',
            name='image_logo',
            field=models.ImageField(null=True, upload_to='design/', verbose_name='imagen logo'),
        ),
        migrations.AlterField(
            model_name='gameimageupload',
            name='image',
            field=models.ImageField(upload_to='media/<django.db.models.fields.CharField>/'),
        ),
    ]
