# Generated by Django 4.1.1 on 2024-08-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0011_styles_image_logo_alter_gameimageupload_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='styles',
            name='image_background_game',
        ),
        migrations.RemoveField(
            model_name='styles',
            name='image_logo_game',
        ),
        migrations.AddField(
            model_name='styles',
            name='image_background_dados',
            field=models.ImageField(null=True, upload_to='design/', verbose_name='imagen fondo Dados'),
        ),
        migrations.AddField(
            model_name='styles',
            name='image_background_precision',
            field=models.ImageField(null=True, upload_to='design/', verbose_name='imagen fondo Precisión'),
        ),
        migrations.AddField(
            model_name='styles',
            name='image_background_puertas',
            field=models.ImageField(null=True, upload_to='design/', verbose_name='imagen fondo Puertas'),
        ),
        migrations.AddField(
            model_name='styles',
            name='image_background_tragamonedas',
            field=models.ImageField(null=True, upload_to='design/', verbose_name='imagen fondo Tragamonedas'),
        ),
        migrations.AddField(
            model_name='styles',
            name='image_box_watch',
            field=models.ImageField(null=True, upload_to='design/', verbose_name='imagen caja reloj'),
        ),
        migrations.AddField(
            model_name='styles',
            name='image_dice_face_five',
            field=models.ImageField(null=True, upload_to='design/', verbose_name='imagen dado cara cinco'),
        ),
        migrations.AddField(
            model_name='styles',
            name='image_dice_face_four',
            field=models.ImageField(null=True, upload_to='design/', verbose_name='imagen dado cara cuatro'),
        ),
        migrations.AddField(
            model_name='styles',
            name='image_dice_face_one',
            field=models.ImageField(null=True, upload_to='design/', verbose_name='imagen dado cara uno'),
        ),
        migrations.AddField(
            model_name='styles',
            name='image_dice_face_six',
            field=models.ImageField(null=True, upload_to='design/', verbose_name='imagen dado cara seis'),
        ),
        migrations.AddField(
            model_name='styles',
            name='image_dice_face_three',
            field=models.ImageField(null=True, upload_to='design/', verbose_name='imagen dado cara tres'),
        ),
        migrations.AddField(
            model_name='styles',
            name='image_dice_face_two',
            field=models.ImageField(null=True, upload_to='design/', verbose_name='imagen dado cara dos'),
        ),
        migrations.AddField(
            model_name='styles',
            name='image_door_center',
            field=models.ImageField(null=True, upload_to='design/', verbose_name='imagen puerta central'),
        ),
        migrations.AddField(
            model_name='styles',
            name='image_door_left',
            field=models.ImageField(null=True, upload_to='design/', verbose_name='imagen puerta izquierda'),
        ),
        migrations.AddField(
            model_name='styles',
            name='image_door_right',
            field=models.ImageField(null=True, upload_to='design/', verbose_name='imagen puerta derecha'),
        ),
        migrations.AddField(
            model_name='styles',
            name='image_logo_dados',
            field=models.ImageField(null=True, upload_to='design/', verbose_name='imagen logo juego Dados'),
        ),
        migrations.AddField(
            model_name='styles',
            name='image_logo_precision',
            field=models.ImageField(null=True, upload_to='design/', verbose_name='imagen logo juego Precisión'),
        ),
        migrations.AddField(
            model_name='styles',
            name='image_logo_puertas',
            field=models.ImageField(null=True, upload_to='design/', verbose_name='imagen logo juego Puertas'),
        ),
        migrations.AddField(
            model_name='styles',
            name='image_logo_tragamoneda',
            field=models.ImageField(null=True, upload_to='design/', verbose_name='imagen logo juego Tragamonedas'),
        ),
    ]
