# Generated by Django 4.1.1 on 2024-08-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0012_remove_styles_image_background_game_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='styles',
            old_name='image_logo_tragamoneda',
            new_name='image_logo_tragamonedas',
        ),
    ]
