# Generated by Django 4.1.1 on 2024-08-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0014_remove_styles_image_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecurrentsession',
            name='gano',
            field=models.BooleanField(default=False, verbose_name='¿ganó la partida?'),
        ),
        migrations.AlterField(
            model_name='match',
            name='win_match',
            field=models.BooleanField(default=False, verbose_name='¿ganó la partida?'),
        ),
    ]
