# Generated by Django 4.1.1 on 2024-08-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppJuegos", "0014_alter_styles_description_winner_and_more"),
        ("AppJuegos", "0015_alter_gamecurrentsession_gano_alter_match_win_match"),
    ]

    operations = []
